# Generated by Django 2.2.3 on 2019-07-16 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name_plural': '북마크'},
        ),
    ]
